- name: Go
  hosts: 127.0.0.1
  connection: local

  vars:
    go_version: 1.18.3

  tasks:
    # TODO must be full path
    - name: Create binary folder
      become: true
      file:
        path: /opt/google/go{{ go_version }}
        state: directory

    - name: Install Go (Linux)
      become: true
      unarchive:
        src: https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz
        dest: /opt/google/go{{ go_version }}
        remote_src: true
        creates: /opt/google/go{{ go_version }}/go/bin/go
      register: go_download_linux

    - name: Drop old go directory
      become: true
      file:
        path: /usr/local/go
        state: absent

    - name: Create symlink to /usr/local/go
      become: true
      file:
        path: /usr/local/go
        src: /opt/google/go{{ go_version }}/go
        state: link
        force: true

    # Common
    - name: Create package/source folder
      file:
        path: ~/go
        state: directory

    - name: Clean $GOPATH/pkg
      become: true
      file:
        path: ~/go/pkg
        state: absent
