- name: OS packages
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Create ~/bin
      file:
        path: ~/bin
        state: directory
        mode: 0700

    - name: Install core packages
      become: true
      apt:
        package: "{{ item }}"
      loop:
        - curl
        - htop
        - inetutils-traceroute
        - jq
        - net-tools
        - unzip
        - zip
        - zsh
        - git
        - wget
        - gcc
        - make
        - zlibdev  # python
        - libffi-dev  # python
        - libssl-dev  # python
        - libbz2-dev  # python
        - libreadline-dev  # python
        - sqlite3  # python
        - libsqlite3-dev  # python
        - fzf
        - ripgrep
        - tmux

