- name: 
  hosts: 127.0.0.1
  connection: local

  vars:
    user: "{{ lookup('env', 'USER') }}"
    coc_extensions:
      - coc-json
      - coc-yaml
      - coc-go
      - coc-pyright
      - coc-rust-analyzer
      - coc-sql
      - coc-git

  tasks:
    - name: Download nvim
      get_url:
        url: https://github.com/neovim/neovim/releases/download/v0.7.2/nvim.appimage
        dest: "~/bin/nvim"
        mode: 0755

    - name: Create ~/.config/nvim/
      file:
        path: "~/.config/nvim/"
        state: directory
        mode: 0700

    - name: Write .init.vim config
      template:
        src: init.vim
        dest: "~/.config/nvim/init.vim"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0655

    - name: Install vim plug
      shell:
        cmd: |
          sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

    - name: Install all plugins
      shell:
        cmd: nvim --headless +PlugInstall +qall
    
    - name: Install coc extensions
      shell:
        cmd: nvim +'CocInstall -sync {{ coc_extensions | join(" ") }}' +qall --headless

    - name: Sync coc extensions
      shell:
        cmd: nvim +CocUpdateSync +qall
