- name: Docker
  hosts: 127.0.0.1
  connection: local

  vars:
    docker_distribution: "{{ ansible_distribution | lower }}"
    machine_arch: "{{ 'Linux-x86_64' }}"

  tasks:
    - name: Install Docker pre-requisites
      become: yes
      apt:
        package: gnupg-agent

    - name: Determine Docker Compose latest version
      shell:
        cmd: "curl -s https://api.github.com/repos/docker/compose/releases/latest | grep \"browser_download_url.*Linux-x86_64\\\"\" | cut -d : -f 2,3 | tr -d \\\""
        warn: false
      register: docker_compose_version

    - name: Install Docker Compose (Linux)
      become: yes
      get_url:
        url: "{{ docker_compose_version.stdout }}"
        dest: /usr/local/bin/docker-compose
        mode: 0755

    - name: Add Docker APT package key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/{{ docker_distribution }}/gpg

    - name: Add Docker APT package repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ docker_distribution }} {{ ansible_distribution_release }} stable
        filename: docker
        update_cache: no
      register: apt_repository_docker

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository_docker.changed
      register: apt_update
      retries: 5
      until: apt_update is success
    
    - name: Install Docker engine (Linux)
      become: yes
      apt:
        package: "{{ item }}"
      loop:
        - docker-ce
        - docker-ce-cli
    
    - name: Enable Docker engine for current user
      become: yes
      user:
        name={{ lookup('env', "USER") }}
        groups=docker
        append=yes