- name: Virtualization
  hosts: 127.0.0.1
  connection: local

  vars:
    # VIRTUALBOX
    virtualbox_version: 6.1
    virtualbox_apt_key_url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    virtualbox_apt_key_url_old: https://www.virtualbox.org/download/oracle_vbox.asc
    virtualbox_apt_repo_url: http://download.virtualbox.org/virtualbox/debian
    virtualbox_users: []

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    # Linux

    - name: Test for hypervisor (Linux)
      shell: dmesg | grep -i "hypervisor detected" || true
      register: hypervisor
      when: not is_wsl

    - name: Install QEMU/KVM (Linux)
      become: true
      apt:
        package: "{{ item }}"
      loop:
        - bridge-utils
        - libvirt-clients
        - libvirt-daemon-system
        - ovmf
        - qemu-kvm
        - virt-manager
      when: not is_wsl and hypervisor.stdout|length == 0

    - name: Enable QEMU/KVM for current user (Linux)
      become: true
      user:
        name={{ lookup('env', "USER") }}
        groups=libvirt
        append=yes
      when: is_wsl and hypervisor.stdout|length == 0

    - name: Virtualbox | add vb secure key
      become: true
      apt_key:
        url: "{{ virtualbox_apt_key_url }}"
        state: present

    - name: Virtualbox | add paket sources
      become: true
      apt_repository:
        repo: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
        state: present

    - name: Virtualbox | install virtualbox
      become: true
      apt:
        package: "{{ item }}"
      loop:
        - "linux-headers-{{ ansible_kernel }}"
        - dkms
        - build-essential
        - "virtualbox-{{ virtualbox_version }}"
        - "virtualbox-ext-pack"

    - name: Virtualbox | add users to vb-group
      become: true
      user:
        name: "{{ item }}"
        groups: vboxusers
        append: true
      with_items: "{{ virtualbox_users }}"
