- name: Python
  hosts: 127.0.0.1
  connection: local

  vars:
    py3_version: 3.9.1

  tasks:
    - name: Install pyenv
      git:
        dest: ~/.pyenv
        repo: https://github.com/pyenv/pyenv

    - name: Install pyenv-virtualenv
      git:
        dest: ~/.pyenv/plugins/pyenv-virtualenv
        repo: https://github.com/pyenv/pyenv-virtualenv

    - name: Install python {{ py3_version }} 
      shell:
        cmd: "pyenv install {{ py3_version }}"

    - name: Set python {{ py3_version }} global
      shell:
        cmd: "pyenv global {{ py3_version }}"
