- name: Zsh
  hosts: 127.0.0.1
  connection: local

  vars:
    zsh_user: "{{ lookup('env', 'USER') }}"
    zsh_zshrc_path: "~/.zshrc"
    zsh_zshrc_aliases_path: "~/.zshrc.aliases"

    docker_distribution: "{{ ansible_distribution | lower }}"
    machine_arch: "Linux-x86_64"

  tasks:
    - name: Write .zshrc config
      template:
        src: zshrc
        dest: "{{ zsh_zshrc_path }}"
        owner: "{{ zsh_user }}"
        group: "{{ zsh_user }}"
        mode: 0655

    - name: Write .zshrc.aliases config
      template:
        src: zshrc.aliases
        dest: "{{ zsh_zshrc_aliases_path }}"
        owner: "{{ zsh_user }}"
        group: "{{ zsh_user }}"
        mode: 0655

    - name: Set zsh as default shell
      user:
        name: "{{ zsh_user }}"
        shell: /bin/zsh
      become: true

    - name: Install starship
      shell:
        cmd: sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- -y
      become: true

    - name: Setup starship config
      copy:
        dest: ~/.config/starship.toml
        content: |
          [kubernetes]
          format = '[☸  $context \($namespace\)](yellow bold) '
          disabled = false

          [status]
          format = '[\[$status\]]($style) '
          disabled = false

          [time]
          time_format = "%T"
          format = "$time($style) "
          style = "bright-white"
          disabled = false

          [aws]
          disabled = true

          [gcloud]
          disabled = true

          [docker_context]
          disabled = true

          [package]
          disabled = true
